### ISSUE TITLE
OGN data stream is not forking w/o LAN cable

### ISSUE THREAD

**Issue by biturbo** [0x74-0x62/flightbox#1]
Hi, is there a possibility that the OGN part will also work without having a LAN cable plugged in to the RPi?
Thanks

**Comment by 0x74-0x62** [comment]
Hi @biturbo! I used the OGN part on an RPi2 without any LAN cable attached. There was just a WiFi dongle connected via USB. Can you provide a bit more information what the problem is?

**Comment by biturbo** [comment]
Hi Thorsten, I am using RPi3 with internal WiFi with latest Jessie build, two RTLSDR dongle, Dump1090, OGN 2.5. Without LAN connection I am getting only ADSB traffic on SkyDemon as soon I connect the LAN cable (DHCP) I am getting FLARM and ADSB traffic. I have a Flarm Mouse for testing at home.
SoftAP is done with hostapd and isc-dhcp-server, hope this helps
Cheers
Serge

**Comment by 0x74-0x62** [comment]
If you still receive ADS-B data after changing the network configuration, the connection between  dump1090 and flightbox as well as flightbox and SkyDemon should be OK. It seems that the link between OGN and flightbox is somehow affected.

Unfortunately, I don't have the exact same hardware setup as you use. Have you tried if the OGN processes (ogn_rf and ogn_decode) run as expected if you start them manually? Just like they are started in the [watchdog script](https://github.com/0x74-0x62/flightbox/blob/master/flightbox_watchdog.py)? Is there any OGN output or log that indicates a problem?

Furthermore, how did you configure your ogn.conf configuration file? In particular, what is the server to which data is sent? The server side that is implemented in [input_network_ogn_server.py](https://github.com/0x74-0x62/flightbox/blob/master/input/input_network_ogn_server.py#L144) should bind to all available interfaces. I'm not sure, however, what exactly happens if you change your network interfaces after the server is up already.

**Comment by biturbo** [comment]
Found the issue, it was the NTP part in then rtlsdr-ogn shellbox service, OGN is looking for a NTP server, therefore it could not be loaded correctly with LAN cable disconnected.

**Comment by 0x74-0x62** [comment]
Thanks for the feedback! How did you solve the problem? Did you find a way to disable NTP in OGN?

**Comment by biturbo** [comment]
Still try to get it sorted out, thought I had a solution with a local time source but w/o success. After a reboot it was working but after a Power off/on I have sadly the same issue again :-( , rebooting is somehow not resetting the NTP stuff.

**Comment by biturbo** [comment]
Get it fixed :-), I start NTP service with the GPS para 127.127.20.0 (time is taking from the GPS source on /dev/gps0) I do not use PPS, then I check if I have a 3D fix then wait some sec after that I then stop NTP to free up the ttyAMA0 for the flightbox and now I start the flightbox and it works :-) . here the source for the NTP: http://open.konspyre.org/blog/2012/10/18/raspberry-flavored-time-a-ntp-server-on-your-pi-tethered-to-a-gps-unit/
